org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop for the newest numbers
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.1
maven_group=com.fishnotify
archives_base_name=fishnotify

# Dependencies
fabric_api_version=0.156.0+26.2
modmenu_version=20.0.1
